<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="eye" params="lr tY">

    
    <link name="${lr}_eye">
      <collision>
        <origin xyz="0 0 ${eye_length/2.0}"
        		rpy="0 0 0" />
        <geometry>
            <box size="${eye_length} ${eye_radius} ${eye_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${eye_length/2.0}"
        		rpy="0 0 0" />
        <geometry>
          <box size="${eye_length} ${eye_radius} ${eye_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${eye_length/2.0}"
        		rpy="0 0 0" />
        <mass value="${Upper_eyeMass}"/>
        <xacro:box_inertia
          m="${Upper_eyeMass}"
          x="${eye_length}"
          y="${eye_radius}"
          z="${eye_radius}"/>
      </inertial>
    </link>

    <gazebo reference="${lr}_eye">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>10000000.0</kp>
      <kd>10000000.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>Gazebo/Green</material>
    </gazebo>


    <joint name="${lr}_eye_hinge" type="fixed">
      <parent link="head"/>
      <child link="${lr}_eye"/>
      <origin 
        xyz = "${eye_X_Offset} ${-tY*(eye_Y_Offset)} ${eye_Z_Offset}"
        rpy = "0 0 ${eye_yaw_Offset}" />
    </joint>
    
    
    <gazebo reference="${lr}_eye">
      <sensor type="camera" name="camera_${lr}_eye">
        <always_on>1</always_on>
        <update_rate>15</update_rate>
        <visualize>true</visualize>
        <camera name="${lr}_eye_cam">
  
            <pose>0 0 0 0 0 0.0</pose>
  
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>400</width>
            <height>400</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.01</near>
            <far>100</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller_${lr}" filename="libgazebo_ros_camera.so">
          <camera_name>stereo/${lr}</camera_name>
          <frame_name>${lr}_eye</frame_name>
          <!-- <hackBaseline>0.07</hackBaseline> -->
          
        </plugin>
      </sensor>
    </gazebo>

  </xacro:macro>

</robot>